pub enum ComputeStyle {
    AcklandAtom,
    Adf,
    Angle,
    AngleLocal,
    AngmomChunk,
    AveSphereAtom,
    BasalAtom,
    BodyLocal,
    Bond,
    BondLocal,
    BornMatrix,
    CentroAtom,
    ChunkAtom,
    ChunkSpreadAtom,
    ClusterAtom,
    FragmentAtom,
    AggregateAtom,
    CnaAtom,
    CnpAtom,
    Com,
    ComChunk,
    ContactAtom,
    CoordAtom,
    CountType,
    DamageAtom,
    Dihedral,
    DihedralLocal,
    DilatationAtom,
    Dipole,
    DipoleTip4p,
    DipoleChunk,
    DipoleTip4pChunk,
    DisplaceAtom,
    Dpd,
    DpdAtom,
    EdpdTempAtom,
    EfieldAtom,
    EfieldWolfAtom,
    EntropyAtom,
    ErotateAsphere,
    ErotateRigid,
    ErotateSphere,
    ErotateSphereAtom,
    EventDisplace,
    Fabric,
    Fep,
    FepTa,
    GlobalAtom,
    GroupGroup,
    Gyration,
    GyrationChunk,
    GyrationShape,
    GyrationShapeChunk,
    HeatFlux,
    HexorderAtom,
    Hma,
    Improper,
    ImproperLocal,
    InertiaChunk,
    Ke,
    KeAtom,
    KeAtomEff,
    KeEff,
    KeRigid,
    Mliap,
    Modify,
    Momentum,
    Msd,
    MsdChunk,
    MsdNongauss,
    NbondAtom,
    OmegaChunk,
    OrientorderAtom,
    Pair,
    PairLocal,
    Pe,
    PeAtom,
    PlasticityAtom,
    Pressure,
    PressureAlchemy,
    PressureUef,
    PropertyAtom,
    PropertyChunk,
    PropertyGrid,
    PropertyLocal,
    PtmAtom,
    Rdf,
    Reduce,
    ReduceRegion,
    ReduceChunk,
    RigidLocal,
    Saed,
    Slice,
    SmdContactRadius,
    SmdDamage,
    SmdHourglassError,
    SmdInternalEnergy,
    SmdPlasticStrain,
    SmdPlasticStrainRate,
    SmdRho,
    SmdTlsphDefgrad,
    SmdTlsphDt,
    SmdTlsphNumNeighs,
    SmdTlsphShape,
    SmdTlsphStrain,
    SmdTlsphStrainRate,
    SmdTlsphStress,
    SmdTriangleVertices,
    SmdUlsphEffm,
    SmdUlsphNumNeighs,
    SmdUlsphStrain,
    SmdUlsphStrainRate,
    SmdUlsphStress,
    SmdVol,
    SnaAtom,
    SnadAtom,
    SnavAtom,
    Snap,
    SnaGrid,
    SnaGridLocal,
    SphEAtom,
    SphRhoAtom,
    SphTAtom,
    Spin,
    StressAtom,
    CentroidStressAtom,
    StressCartesian,
    StressCylinder,
    StressSpherical,
    StressMop,
    StressMopProfile,
    ForceTally,
    HeatFluxTally,
    HeatFluxVirialTally,
    PeTally,
    PeMolTally,
    StressTally,
    TdpdCcAtom,
    Temp,
    TempAsphere,
    TempBody,
    TempChunk,
    TempCom,
    TempCs,
    TempDeform,
    TempDeformEff,
    TempDrude,
    TempEff,
    TempPartial,
    TempProfile,
    TempRamp,
    TempRegion,
    TempRegionEff,
    TempRotate,
    TempSphere,
    TempUef,
    Ti,
    TorqueChunk,
    Vacf,
    VcmChunk,
    ViscosityCos,
    VoronoiAtom,
    Xrd,
    InvalidComputeStyle,
}

impl From<&str> for ComputeStyle {
    fn from(value: &str) -> Self {
        #[allow(clippy::enum_glob_use)]
        use ComputeStyle::*;
        match value {
            "ackland/atom" => AcklandAtom,
            "adf" => Adf,
            "angle" => Angle,
            "angle/local" => AngleLocal,
            "angmom/chunk" => AngmomChunk,
            "ave/sphere/atom" => AveSphereAtom,
            "basal/atom" => BasalAtom,
            "body/local" => BodyLocal,
            "bond" => Bond,
            "bond/local" => BondLocal,
            "born/matrix" => BornMatrix,
            "centro/atom" => CentroAtom,
            "chunk/atom" => ChunkAtom,
            "chunk/spread/atom" => ChunkSpreadAtom,
            "cluster/atom" => ClusterAtom,
            "fragment/atom" => FragmentAtom,
            "aggregate/atom" => AggregateAtom,
            "cna/atom" => CnaAtom,
            "cnp/atom" => CnpAtom,
            "com" => Com,
            "com/chunk" => ComChunk,
            "contact/atom" => ContactAtom,
            "coord/atom" => CoordAtom,
            "count/type" => CountType,
            "damage/atom" => DamageAtom,
            "dihedral" => Dihedral,
            "dihedral/local" => DihedralLocal,
            "dilatation/atom" => DilatationAtom,
            "dipole" => Dipole,
            "dipole/tip4p" => DipoleTip4p,
            "dipole/chunk" => DipoleChunk,
            "dipole/tip4p/chunk" => DipoleTip4pChunk,
            "displace/atom" => DisplaceAtom,
            "dpd" => Dpd,
            "dpd/atom" => DpdAtom,
            "edpd/temp/atom" => EdpdTempAtom,
            "efield/atom" => EfieldAtom,
            "efield/wolf/atom" => EfieldWolfAtom,
            "entropy/atom" => EntropyAtom,
            "erotate/asphere" => ErotateAsphere,
            "erotate/rigid" => ErotateRigid,
            "erotate/sphere" => ErotateSphere,
            "erotate/sphere/atom" => ErotateSphereAtom,
            "event/displace" => EventDisplace,
            "fabric" => Fabric,
            "fep" => Fep,
            "fep/ta" => FepTa,
            "global/atom" => GlobalAtom,
            "group/group" => GroupGroup,
            "gyration" => Gyration,
            "gyration/chunk" => GyrationChunk,
            "gyration/shape" => GyrationShape,
            "gyration/shape/chunk" => GyrationShapeChunk,
            "heat/flux" => HeatFlux,
            "hexorder/atom" => HexorderAtom,
            "hma" => Hma,
            "improper" => Improper,
            "improper/local" => ImproperLocal,
            "inertia/chunk" => InertiaChunk,
            "ke" => Ke,
            "ke/atom" => KeAtom,
            "ke/atom/eff" => KeAtomEff,
            "ke/eff" => KeEff,
            "ke/rigid" => KeRigid,
            "mliap" => Mliap,
            "modify" => Modify,
            "momentum" => Momentum,
            "msd" => Msd,
            "msd/chunk" => MsdChunk,
            "msd/nongauss" => MsdNongauss,
            "nbond/atom" => NbondAtom,
            "omega/chunk" => OmegaChunk,
            "orientorder/atom" => OrientorderAtom,
            "pair" => Pair,
            "pair/local" => PairLocal,
            "pe" => Pe,
            "pe/atom" => PeAtom,
            "plasticity/atom" => PlasticityAtom,
            "pressure" => Pressure,
            "pressure/alchemy" => PressureAlchemy,
            "pressure/uef" => PressureUef,
            "property/atom" => PropertyAtom,
            "property/chunk" => PropertyChunk,
            "property/grid" => PropertyGrid,
            "property/local" => PropertyLocal,
            "ptm/atom" => PtmAtom,
            "rdf" => Rdf,
            "reduce" => Reduce,
            "reduce/region" => ReduceRegion,
            "reduce/chunk" => ReduceChunk,
            "rigid/local" => RigidLocal,
            "saed" => Saed,
            "slice" => Slice,
            "smd/contact/radius" => SmdContactRadius,
            "smd/damage" => SmdDamage,
            "smd/hourglass/error" => SmdHourglassError,
            "smd/internal/energy" => SmdInternalEnergy,
            "smd/plastic/strain" => SmdPlasticStrain,
            "smd/plastic/strain/rate" => SmdPlasticStrainRate,
            "smd/rho" => SmdRho,
            "smd/tlsph/defgrad" => SmdTlsphDefgrad,
            "smd/tlsph/dt" => SmdTlsphDt,
            "smd/tlsph/num/neighs" => SmdTlsphNumNeighs,
            "smd/tlsph/shape" => SmdTlsphShape,
            "smd/tlsph/strain" => SmdTlsphStrain,
            "smd/tlsph/strain/rate" => SmdTlsphStrainRate,
            "smd/tlsph/stress" => SmdTlsphStress,
            "smd/triangle/vertices" => SmdTriangleVertices,
            "smd/ulsph/effm" => SmdUlsphEffm,
            "smd/ulsph/num/neighs" => SmdUlsphNumNeighs,
            "smd/ulsph/strain" => SmdUlsphStrain,
            "smd/ulsph/strain/rate" => SmdUlsphStrainRate,
            "smd/ulsph/stress" => SmdUlsphStress,
            "smd/vol" => SmdVol,
            "sna/atom" => SnaAtom,
            "snad/atom" => SnadAtom,
            "snav/atom" => SnavAtom,
            "snap" => Snap,
            "sna/grid" => SnaGrid,
            "sna/grid/local" => SnaGridLocal,
            "sph/e/atom" => SphEAtom,
            "sph/rho/atom" => SphRhoAtom,
            "sph/t/atom" => SphTAtom,
            "spin" => Spin,
            "stress/atom" => StressAtom,
            "centroid/stress/atom" => CentroidStressAtom,
            "stress/cartesian" => StressCartesian,
            "stress/cylinder" => StressCylinder,
            "stress/spherical" => StressSpherical,
            "stress/mop" => StressMop,
            "stress/mop/profile" => StressMopProfile,
            "force/tally" => ForceTally,
            "heat/flux/tally" => HeatFluxTally,
            "heat/flux/virial/tally" => HeatFluxVirialTally,
            "pe/tally" => PeTally,
            "pe/mol/tally" => PeMolTally,
            "stress/tally" => StressTally,
            "tdpd/cc/atom" => TdpdCcAtom,
            "temp" => Temp,
            "temp/asphere" => TempAsphere,
            "temp/body" => TempBody,
            "temp/chunk" => TempChunk,
            "temp/com" => TempCom,
            "temp/cs" => TempCs,
            "temp/deform" => TempDeform,
            "temp/deform/eff" => TempDeformEff,
            "temp/drude" => TempDrude,
            "temp/eff" => TempEff,
            "temp/partial" => TempPartial,
            "temp/profile" => TempProfile,
            "temp/ramp" => TempRamp,
            "temp/region" => TempRegion,
            "temp/region/eff" => TempRegionEff,
            "temp/rotate" => TempRotate,
            "temp/sphere" => TempSphere,
            "temp/uef" => TempUef,
            "ti" => Ti,
            "torque/chunk" => TorqueChunk,
            "vacf" => Vacf,
            "vcm/chunk" => VcmChunk,
            "viscosity/cos" => ViscosityCos,
            "voronoi/atom" => VoronoiAtom,
            "xrd" => Xrd,
            _ => InvalidComputeStyle,
        }
    }
}
